packages:
  - "."
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  canvas: false
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: false
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - canvas
  - sharp
